- name: variable to print
  hosts: web 
  vars: 
    COURSE: "DevOps" 
    DURATION: "5 hours"
  tasks: 
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: "Hi {{COURSE}} is {{DURATION}}"