- name: variable to print
  hosts: web 
  vars_prompt: 
  - name: "COURSE"
    prompt: "please enter course"
  - name: "DURATION"
    prompt: "please  enter duration"
  tasks: 
   - name: variables from prompt
     ansible.builtin.debug:
       msg: "Hi {{COURSE}} is {{DURATION}}"