- name: variable to print
  hosts: web 
  vars: 
    COURSE: "Ansible from play" 
  vars_files: 
  - vars.yaml 
  vars_prompt: 
  - name: COURSE
    prompt: please enter course
  tasks: 
  - name: Print the task level varaible
    vars: 
      COURSE: "Ansible from task" 
    ansible.builtin.debug:
      msg: "Hi {{COURSE}}"