- name: create expense user if doesnt exit
  hosts: web 
  become: true
  tasks: 
  - name: check user exits or not
    ansible.builtin.command: id divya 
    register: USER  
    ignore_errors: true
  - name: print user info
    ansible.builtin.debug:
      msg: "{{ USER }}"
    
  - name: create user
    ansible.builtin.command: adduser divya 
    when:  USER.rc != 0