- name: install and run nginx
  hosts: web # target node
  become: true # root access
  tasks: 
  - name: nginx install
    ansible.builtin.dnf:
      name: nginx
      state: present 
    when: ansible_os_family == "RedHat"

  - name: nginx install
    ansible.builtin.apt:
      name: nginx
      state: present 
    when: ansible_os_family == "Debian"
