- name: loops demo
  hosts: local
  connection: local 
  tasks:
  - name: print person name
    ansible.builtin.debug:
      msg: "Hi {{ item }}"
    loop: 
    - divya
    - padmavathamma
    - venkateswar reddy
    - mohan
    - prakash
    