- name: install packages using loop
  hosts: web
  become: true
  tasks: 
  - name: install packages
    ansible.builtin.package:
      name: {{ item }}
      state: present
    loop: 
    - httpd
    - postfix
   