- name:  functions/filters
  hosts: web
  tasks:
  - name: use filters
    ansible.builtin.debug:
      msg: "Hi {{ COURSE | default('Ansible') }}" 
  - name: use upper filter
    vars: 
      greeting: "hi ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}" 
  - name: use unique filter
    vars: 
      number: [3, 4, 5 , 3, 6]
    ansible.builtin.debug:
      msg: "{{ number | unique }}" 
  - name: dict/map to list
    vars: 
      course:
        name: 'ansible'
        duration: 10
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"  
  - name: dict/map to list
    vars: 
      course:
      - { name: 'ansible', duration: 5}
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"  