- name: command vs shell
  hosts: local
  connection: local 
  tasks:
  - name: execute command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # login to the server and execute the commands
  - name: check the process
    ansible.builtin.command: ps -ef | grep ssh
    register: output
    