- name: create ec2 instance
  hosts: local
  connection: local
  vars: 
    subnet_id: "subnet-0509f144a358e12de"
    security_id: "sg-08eed4ca0fd852a9e"
    image_id: "ami-09c813fb71547fc4f"
    instances: 
    - frontend
    - backend
    - mysql
    zone_name: dev.divyavutakanti.com
  tasks: 
  - name: create instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ security_id }}"
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: instances_info
  - name: print instances_info
    ansible.builtin.debug: 
      msg: "{{ instances_info }}"
  # - name: "route53"
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone_name }}"
  #     record: 
  #     type: A
  #     ttl: 7200
  #     value: {{ item.instances[0].private_ip_address}}
  #     wait: true
  #   loop: "{{ instances_info.results }}"
