- name: install multiple utills
  hosts: web 
  # remote_user: root
  become: yes
  vars: 
    install_utills: 
    - mysql
    - nginx
  tasks: 
  - name: install the utils
    ansible.builtin.package: 
      name: "{{ item }}"
      state: present 
    loop: "{{ install_utills }}"